In [1]:
import pandas as pd 
import numpy as np

In [2]:
flights = pd.read_csv('data/flights.csv')
flights.head(10)

,travelCode,userCode,from,to,flightType,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
5,2,0,Salvador (BH),Aracaju (SE),firstClass,1531.92,2.16,830.86,CloudFy,10/12/2019
6,3,0,Aracaju (SE),Campo Grande (MS),economic,743.54,1.69,650.10,Rainbow,10/17/2019
7,3,0,Campo Grande (MS),Aracaju (SE),economic,877.56,1.69,650.10,Rainbow,10/20/2019
8,4,0,Recife (PE),Florianopolis (SC),economic,803.39,1.76,676.53,Rainbow,10/24/2019
9,4,0,Florianopolis (SC),Recife (PE),economic,695.30,1.76,676.53,Rainbow,10/26/2019

In [3]:
# travelCode and userCode are identifier for a complete unique travel . And userCode is identifier for a unique user . 
# we will drop travelCode , it is not needed to model creation .

flights.drop(['travelCode'],axis = 1 , inplace = True)

In [4]:
# dropping usercode 
flights.drop(['userCode'],axis = 1 , inplace = True)

In [5]:
flights.head()

,from,to,flightType,price,time,distance,agency,date
0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019

In [6]:
# one hot encoding the "from" and "to" column 

from sklearn.preprocessing import OneHotEncoder 

from_to_encoder = OneHotEncoder(sparse_output=False)

cols = ['from' , 'to']

encoded_arr = from_to_encoder.fit_transform(flights[cols])

encoded_arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
from_to_encoder.categories_

[array(['Aracaju (SE)', 'Brasilia (DF)', 'Campo Grande (MS)',
        'Florianopolis (SC)', 'Natal (RN)', 'Recife (PE)',
        'Rio de Janeiro (RJ)', 'Salvador (BH)', 'Sao Paulo (SP)'],
       dtype=object),
 array(['Aracaju (SE)', 'Brasilia (DF)', 'Campo Grande (MS)',
        'Florianopolis (SC)', 'Natal (RN)', 'Recife (PE)',
        'Rio de Janeiro (RJ)', 'Salvador (BH)', 'Sao Paulo (SP)'],
       dtype=object)]

In [8]:
encoded_arr.shape

(271888, 18)

In [9]:
flights['flightType'].unique()

array(['firstClass', 'economic', 'premium'], dtype=object)

In [10]:
# There is ordinal order in flightType so we will do ordinal encoding

from sklearn.preprocessing import OrdinalEncoder
flightType_encoder = OrdinalEncoder(categories=[['firstClass' ,'premium' , 'economic']])

encoded_flightType = flightType_encoder.fit_transform(flights[['flightType']])

In [11]:
# Scaling the encoded_flightType
from sklearn.preprocessing import StandardScaler 
flightType_scaler = StandardScaler()
encoded_flightType_scaled = flightType_scaler.fit_transform(encoded_flightType)

In [12]:
flights.head()

,from,to,flightType,price,time,distance,agency,date
0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019

In [13]:
target = 'price'

In [14]:
# processing time and distance features
from sklearn.preprocessing import PowerTransformer

cols = ['time' , 'distance']
time_dis_pt = PowerTransformer()

time_distance_transformed = time_dis_pt.fit_transform(flights[cols])
time_distance_transformed

array([[ 0.61272056,  0.61776595],
       [ 0.61272056,  0.61776595],
       [ 0.42214525,  0.42942277],
       ...,
       [ 0.76632167,  0.77676493],
       [-0.41456697, -0.3933792 ],
       [-0.41456697, -0.3933792 ]])

In [15]:
# processing agency 


agency_ohe = OneHotEncoder(sparse_output=False)
agency_encoded = agency_ohe.fit_transform(flights[['agency']])
agency_encoded

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [16]:
agency_ohe.categories_

[array(['CloudFy', 'FlyingDrops', 'Rainbow'], dtype=object)]

In [17]:
# # Processing date 
# # converting date feature to datetime
# flights['date'] = pd.to_datetime(flights['date'])

# # creating year , month , day_of_week , day_of_month 
# flights['year'] = flights['date'].dt.year
# flights['month'] = flights['date'].dt.month
# flights['day_of_week'] = flights['date'].dt.dayofweek # Monday = 0 , sunday = 6
# flights['day_of_month'] = flights['date'].dt.day

In [18]:
# Processing date

flights["date"] = pd.to_datetime(flights["date"])

# Basic date features
flights["year"] = flights["date"].dt.year
flights["month"] = flights["date"].dt.month
flights["day_of_week"] = flights["date"].dt.dayofweek
flights["day_of_month"] = flights["date"].dt.day

# New engineered features

# Quarter
flights["quarter"] = flights["date"].dt.quarter

# Weekend flag
flights["is_weekend"] = (
    flights["day_of_week"].isin([5, 6])
).astype(int)

# Cyclical month encoding
flights["month_sin"] = np.sin(
    2 * np.pi * flights["month"] / 12
)

flights["month_cos"] = np.cos(
    2 * np.pi * flights["month"] / 12
)

# Cyclical day of week encoding
flights["dow_sin"] = np.sin(
    2 * np.pi * flights["day_of_week"] / 7
)

flights["dow_cos"] = np.cos(
    2 * np.pi * flights["day_of_week"] / 7
)

flights.head()

,from,to,flightType,price,time,distance,agency,date,year,month,day_of_week,day_of_month,quarter,is_weekend,month_sin,month_cos,dow_sin,dow_cos
0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,2019-09-26,2019,9,3,26,3,0,-1.000000,-1.836970e-16,0.433884,-0.900969
1,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,2019-09-30,2019,9,0,30,3,0,-1.000000,-1.836970e-16,0.000000,1.000000
2,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,2019-10-03,2019,10,3,3,4,0,-0.866025,5.000000e-01,0.433884,-0.900969
3,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,2019-10-04,2019,10,4,4,4,0,-0.866025,5.000000e-01,-0.433884,-0.900969
4,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,2019-10-10,2019,10,3,10,4,0,-0.866025,5.000000e-01,0.433884,-0.900969

In [19]:
flights.head()

,from,to,flightType,price,time,distance,agency,date,year,month,day_of_week,day_of_month,quarter,is_weekend,month_sin,month_cos,dow_sin,dow_cos
0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,2019-09-26,2019,9,3,26,3,0,-1.000000,-1.836970e-16,0.433884,-0.900969
1,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,2019-09-30,2019,9,0,30,3,0,-1.000000,-1.836970e-16,0.000000,1.000000
2,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,2019-10-03,2019,10,3,3,4,0,-0.866025,5.000000e-01,0.433884,-0.900969
3,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,2019-10-04,2019,10,4,4,4,0,-0.866025,5.000000e-01,-0.433884,-0.900969
4,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,2019-10-10,2019,10,3,10,4,0,-0.866025,5.000000e-01,0.433884,-0.900969

In [20]:
# scaling year , month , day_of_week , day_of_month 
date_cols = [
    "year",
    "month",
    "day_of_week",
    "day_of_month",
    "quarter",
    "is_weekend",
    "month_sin",
    "month_cos",
    "dow_sin",
    "dow_cos"
]

date_scaler = StandardScaler()

date_features_scaled = date_scaler.fit_transform(
    flights[date_cols]
)
date_features_scaled

array([[-1.55368936,  0.66336123, -0.22562083, ..., -0.11247601,
         0.8817433 , -0.70110144],
       [-1.55368936,  0.66336123, -2.03773229, ..., -0.11247601,
         0.10173328,  1.89126078],
       [-1.55368936,  0.94063034, -0.22562083, ...,  0.59456095,
         0.8817433 , -0.70110144],
       ...,
       [-0.53344655,  0.10882299, -2.03773229, ..., -1.33709994,
         0.10173328,  1.89126078],
       [-0.53344655,  0.10882299, -0.22562083, ..., -1.33709994,
         0.8817433 , -0.70110144],
       [-0.53344655,  0.10882299,  1.58649062, ..., -1.33709994,
        -1.30379619,  1.37781165]])

In [21]:
final_matrix = np.concatenate([encoded_arr , encoded_flightType_scaled , time_distance_transformed , agency_encoded , date_features_scaled] , axis = 1)
final_matrix.shape

(271888, 34)

In [22]:
# saving all the encoders for future use using pickle : save in artifacts folder
#  save from_to_encoder , flightType_encoder , flightType_scaler , time_dis_pt ,agency_ohe , date_scaler , then save a list of date columns which needs to be first created from user input and then needs to be scaled using date_scaler : cols
import pickle 
objects_to_save = {
    "from_to_encoder.pkl" : from_to_encoder,
    "flightType_encoder.pkl": flightType_encoder,
    "flightType_scaler.pkl" : flightType_scaler,
    "time_dis_pt.pkl" : time_dis_pt,
    "agency_ohe.pkl" : agency_ohe,
    "date_scaler.pkl" : date_scaler , 
    "date_cols.pkl" : date_cols
}

for filename , obj in objects_to_save.items():
    with open(f"artifacts/{filename}" , "wb") as f:
        pickle.dump(obj , f)

print("All the encoders and scalers saved successfully")

All the encoders and scalers saved successfully

Saving the Feature Names

In [23]:
# Feature names for from and to OHE
from_to_feature_names = from_to_encoder.get_feature_names_out(
    ['from', 'to']
).tolist()

# Flight type
flight_type_feature_names = ["flightType_scaled"]

# Time and distance
time_distance_feature_names = ["time_transformed",
                               "distance_transformed"]

# Agency OHE
agency_feature_names = agency_ohe.get_feature_names_out(
    ['agency']
).tolist()

# Date features
date_feature_names = [
    f"{col}_scaled" for col in date_cols
]

# Final feature names
feature_names = (
    from_to_feature_names +
    flight_type_feature_names +
    time_distance_feature_names +
    agency_feature_names +
    date_feature_names
)

print(len(feature_names))

# save the feature names 
with open('artifacts/feature_names.pkl' , 'wb') as f:
    pickle.dump(feature_names , f)

34

In [23]:
# creating the target variable y 

y = flights[target].values

# saving the Model ready data matrix : final_matrix and the targer feature array : y 

np.savez("data/flights_cleaned.npz" , X = final_matrix , y = y)

In [24]:
# Saving list of unique values for necessary features.It will be used in Flask API .
import pickle
# saving agency list
agency_list = sorted(flights['agency'].unique().tolist())
with open("artifacts/agency_list.pkl" , "wb") as f:
    pickle.dump(agency_list , f)

In [25]:
# saving date range 
min_date = flights['date'].min()
max_date = flights['date'].max()

date_range = {"min_date": min_date,
"max_date": max_date}

with open("artifacts/date_range.pkl" , "wb") as f:
    pickle.dump(date_range , f)

In [26]:
min_date , max_date

(Timestamp('2019-09-26 00:00:00'), Timestamp('2023-07-24 00:00:00'))

In [27]:
flight_type_list = sorted(flights['flightType'].unique().tolist())
with open("artifacts/flight_type_list.pkl" , "wb") as f:
    pickle.dump(flight_type_list , f)

In [28]:
flights.columns

Index(['from', 'to', 'flightType', 'price', 'time', 'distance', 'agency',
       'date', 'year', 'month', 'day_of_week', 'day_of_month', 'quarter',
       'is_weekend', 'month_sin', 'month_cos', 'dow_sin', 'dow_cos'],
      dtype='object')

In [29]:
flights['from'].unique()

array(['Recife (PE)', 'Florianopolis (SC)', 'Brasilia (DF)',
       'Aracaju (SE)', 'Salvador (BH)', 'Campo Grande (MS)',
       'Sao Paulo (SP)', 'Natal (RN)', 'Rio de Janeiro (RJ)'],
      dtype=object)

In [30]:
mask = (
    (flights["from"] == "Recife (PE)") &
    (flights["to"] == "Florianopolis (SC)")
)

distances = flights.loc[mask, "distance"]
print(distances.unique())

# ----------------------------------------------

mask = (
    (flights["from"] == 'Brasilia (DF)') &
    (flights["to"] == "Florianopolis (SC)")
)

distances = flights.loc[mask, "distance"]
print(distances.unique())

[676.53]
[637.56]

In [31]:
# getting unique distances between each unique combination of from and to cities


distance_map = (
    flights
    .groupby(["from", "to"])["distance"]
    .unique()
    .reset_index()
)

print(distance_map.head(10))

            from                   to  distance
0   Aracaju (SE)        Brasilia (DF)  [425.98]
1   Aracaju (SE)    Campo Grande (MS)   [650.1]
2   Aracaju (SE)   Florianopolis (SC)  [808.85]
3   Aracaju (SE)           Natal (RN)  [176.33]
4   Aracaju (SE)          Recife (PE)  [555.74]
5   Aracaju (SE)  Rio de Janeiro (RJ)  [597.61]
6   Aracaju (SE)        Salvador (BH)  [830.86]
7   Aracaju (SE)       Sao Paulo (SP)  [392.76]
8  Brasilia (DF)         Aracaju (SE)  [425.98]
9  Brasilia (DF)    Campo Grande (MS)   [277.7]

We can see that the distance between each unique from and to location is different. But also a single unique distance for for each unique pair of for and to cities.

Basically , we can directly infer the distance between from and to cities.We will save this mapping as a dictionary for later use in our Flask API.

In [32]:
city_pair_distance = {}

for _,row in distance_map.iterrows():
    from_city = row["from"]
    to_city = row["to"]
    distance = row["distance"][0]
    #forward mapping
    city_pair_distance[(from_city , to_city)] = distance
    #reverse mapping
    city_pair_distance[(to_city , from_city)] = distance


with open("artifacts/city_pair_distance.pkl" , "wb") as f:
    pickle.dump(city_pair_distance , f)

In [33]:
# Now inspecting for time feature

# Checking how many unique time values are there for each unique from and to city pair

time_variation = (
    flights
    .groupby(["from", "to"])["time"]
    .nunique()
    .reset_index(name="unique_time_count")
)
time_variation.sort_values("unique_time_count", ascending=False)

                   from                   to  unique_time_count
0          Aracaju (SE)        Brasilia (DF)                  1
44          Recife (PE)           Natal (RN)                  1
50  Rio de Janeiro (RJ)    Campo Grande (MS)                  1
49  Rio de Janeiro (RJ)        Brasilia (DF)                  1
48  Rio de Janeiro (RJ)         Aracaju (SE)                  1
..                  ...                  ...                ...
29   Florianopolis (SC)  Rio de Janeiro (RJ)                  1
30   Florianopolis (SC)        Salvador (BH)                  1
31   Florianopolis (SC)       Sao Paulo (SP)                  1
32           Natal (RN)         Aracaju (SE)                  1
69       Sao Paulo (SP)        Salvador (BH)                  1

[70 rows x 3 columns]

For time also , there is a single unique time for each unique pair of from and to cities. We will save this mapping as a dictionary for later use in our Flask API.

In [34]:
route_time_df = (
    flights
    .groupby(["from", "to"])["time"]
    .agg(lambda x: x.mode().iloc[0])
    .reset_index()
)

city_pair_time = {}

for _, row in route_time_df.iterrows():
    from_city = row["from"]
    to_city = row["to"]
    time_val = row["time"]

    # forward
    city_pair_time[(from_city, to_city)] = time_val
    # reverse
    city_pair_time[(to_city, from_city)] = time_val


with open("artifacts/city_pair_time.pkl", "wb") as f:
    pickle.dump(city_pair_time, f)

Completed flights dataset preprocessing